# frozen_string_literal: true

require_relative "test_helper"
require "fond/routes"
require "tmpdir"

class ClientCodegenTest < Minitest::Test
  def setup
    Fond::Registry.reset!
  end

  def test_pages_ts_content
    index_page = build_page("ClCoOrdersIndexPage", props: build_props(:total, Integer))
    show_page = build_page("ClCoOrdersShowPage", props: build_props(:name, String))

    generator = Fond::Codegen::Generator.new(
      pages: [show_page, index_page],
      bindings: [
        binding_for(show_page, "/orders/:id", %w[id]),
        binding_for(index_page, "/orders", [])
      ]
    )

    expected = <<~TS
      // Generated by fond. Do not edit.
      // Regenerate with: bin/rails fond:codegen

      export const pages = {
        "cl_co_orders_index": () => import("../pages/cl_co_orders_index"),
        "cl_co_orders_show": () => import("../pages/cl_co_orders_show"),
      };
      export type PageComponentName = keyof typeof pages;
    TS

    assert_equal expected, generator.pages_ts
  ensure
    remove_pages(:ClCoOrdersIndexPage, :ClCoOrdersShowPage)
  end

  def test_hooks_ts_content
    index_page = build_page("ClCoHooksIndexPage", props: build_props(:total, Integer))
    show_page = build_page("ClCoHooksShowPage", props: build_props(:name, String), params: build_params(:id, Integer))

    generator = Fond::Codegen::Generator.new(
      pages: [show_page, index_page],
      bindings: [
        binding_for(show_page, "/hooks/:id", %w[id]),
        binding_for(index_page, "/hooks", [])
      ]
    )

    expected = <<~TS
      // Generated by fond. Do not edit.
      // Regenerate with: bin/rails fond:codegen

      import { usePageProps } from "fond";
      import type { ClCoHooksIndexProps, ClCoHooksShowProps } from "./types";

      export function useClCoHooksIndex(): ClCoHooksIndexProps {
        return usePageProps<ClCoHooksIndexProps>("cl_co_hooks_index");
      }

      export function useClCoHooksShow(): ClCoHooksShowProps {
        return usePageProps<ClCoHooksShowProps>("cl_co_hooks_show");
      }
    TS

    assert_equal expected, generator.hooks_ts
  ensure
    remove_pages(:ClCoHooksIndexPage, :ClCoHooksShowPage)
  end

  def test_paths_ts_covers_all_signature_shapes
    # required :id, present on Params -> Pick/Omit
    show_page = build_page("ClCoPathsShowPage", props: build_props(:name, String), params: build_params(:id, Integer))
    # optional Params only -> Partial<X>
    index_page = build_page("ClCoPathsIndexPage", props: build_props(:total, Integer), params: build_params(:page, Integer))
    # no Params struct, no required params -> ()
    plain_page = build_page("ClCoPathsPlainPage", props: build_props(:ok, T::Boolean))
    # required :token, not a field of Params -> fallback with & Partial<X>
    legacy_page = build_page(
      "ClCoPathsLegacyPage",
      props: build_props(:ok, T::Boolean),
      params: build_params(:page, Integer)
    )
    # required :token, no Params struct at all -> plain fallback, no import
    bare_page = build_page("ClCoPathsBarePage", props: build_props(:ok, T::Boolean))

    generator = Fond::Codegen::Generator.new(
      pages: [show_page, index_page, plain_page, legacy_page, bare_page],
      bindings: [
        binding_for(show_page, "/paths/:id", %w[id]),
        binding_for(index_page, "/paths", []),
        binding_for(plain_page, "/paths/plain", []),
        binding_for(legacy_page, "/paths/legacy/:token", %w[token]),
        binding_for(bare_page, "/paths/bare/:token", %w[token])
      ]
    )

    ts = generator.paths_ts

    assert_includes ts, "import type { ClCoPathsIndexParams, ClCoPathsLegacyParams, ClCoPathsShowParams } from \"./types\";"
    assert_includes ts, "clCoPathsShow: (params: Pick<ClCoPathsShowParams, \"id\"> & Partial<Omit<ClCoPathsShowParams, \"id\">>) =>\n    buildPath(\"/paths/:id\", [\"id\"], params),"
    assert_includes ts, "clCoPathsIndex: (params?: Partial<ClCoPathsIndexParams>) =>\n    buildPath(\"/paths\", [], params),"
    assert_includes ts, "clCoPathsPlain: () =>\n    buildPath(\"/paths/plain\", []),"
    assert_includes ts, "clCoPathsLegacy: (params: { token: string | number } & Partial<ClCoPathsLegacyParams>) =>\n    buildPath(\"/paths/legacy/:token\", [\"token\"], params),"
    assert_includes ts, "clCoPathsBare: (params: { token: string | number }) =>\n    buildPath(\"/paths/bare/:token\", [\"token\"], params),"
  ensure
    remove_pages(:ClCoPathsShowPage, :ClCoPathsIndexPage, :ClCoPathsPlainPage, :ClCoPathsLegacyPage, :ClCoPathsBarePage)
  end

  def test_nested_module_page_naming
    outer = Module.new
    Object.const_set(:ClCoAdmin, outer)
    inner = Module.new
    outer.const_set(:Orders, inner)
    page = Class.new(Fond::Page)
    inner.const_set(:IndexPage, page)
    page.const_set(:Props, build_props(:total, Integer))

    assert_equal "cl_co_admin/orders/index", page.component_name

    generator = Fond::Codegen::Generator.new(
      pages: [page],
      bindings: [binding_for(page, "/admin/orders", [])]
    )

    assert_includes generator.hooks_ts, "export function useClCoAdminOrdersIndex(): ClCoAdminOrdersIndexProps {"
    assert_includes generator.paths_ts, "clCoAdminOrdersIndex: () =>\n    buildPath(\"/admin/orders\", []),"
  ensure
    Object.send(:remove_const, :ClCoAdmin) if Object.const_defined?(:ClCoAdmin)
  end

  def test_determinism_across_all_files
    a_page = build_page("ClCoDetAPage", props: build_props(:a, Integer))
    b_page = build_page("ClCoDetBPage", props: build_props(:b, Integer))
    bindings = [binding_for(a_page, "/det-a", []), binding_for(b_page, "/det-b", [])]

    first = Fond::Codegen::Generator.new(pages: [b_page, a_page], bindings: bindings)
    second = Fond::Codegen::Generator.new(pages: [b_page, a_page], bindings: bindings)

    assert_equal first.pages_ts, second.pages_ts
    assert_equal first.hooks_ts, second.hooks_ts
    assert_equal first.paths_ts, second.paths_ts
  ensure
    remove_pages(:ClCoDetAPage, :ClCoDetBPage)
  end

  def test_write_and_check_roundtrip_over_four_files
    page = build_page("ClCoWritePage", props: build_props(:a, Integer))
    generator = Fond::Codegen::Generator.new(pages: [page], bindings: [binding_for(page, "/write", [])])

    Dir.mktmpdir do |dir|
      changed = generator.write(dir)
      names = %w[types.ts pages.ts hooks.ts paths.ts]
      expected_paths = names.map { |n| File.join(dir, n) }
      assert_equal expected_paths.sort, changed.sort
      assert generator.check(dir)

      assert_equal [], generator.write(dir)

      File.write(File.join(dir, "pages.ts"), "tampered")
      refute generator.check(dir)

      recovered = generator.write(dir)
      assert_equal [File.join(dir, "pages.ts")], recovered
      assert generator.check(dir)
    end
  ensure
    remove_pages(:ClCoWritePage)
  end

  def test_pages_import_prefix_override
    page = build_page("ClCoPrefixPage", props: build_props(:a, Integer))
    original_prefix = Fond.config.pages_import_prefix
    Fond.config.pages_import_prefix = "@/pages/"

    generator = Fond::Codegen::Generator.new(pages: [page], bindings: [binding_for(page, "/prefix", [])])
    assert_includes generator.pages_ts, 'import("@/pages/cl_co_prefix")'
  ensure
    Fond.config.pages_import_prefix = original_prefix
    remove_pages(:ClCoPrefixPage)
  end

  def test_hooks_ts_mutation_redirect_only_and_props
    create_mutation = build_mutation("ClCoMutCreateMutation", params: build_params(:name, String))
    update_mutation = build_mutation(
      "ClCoMutUpdateMutation",
      params: build_params(:total, Integer),
      props: build_props(:ok, T::Boolean)
    )

    generator = Fond::Codegen::Generator.new(
      pages: [],
      bindings: [],
      mutations: [create_mutation, update_mutation],
      mutation_bindings: [
        mutation_binding_for(create_mutation, "/mut", "POST", []),
        mutation_binding_for(update_mutation, "/mut/:id", "PATCH", %w[id])
      ]
    )

    expected = <<~TS
      // Generated by fond. Do not edit.
      // Regenerate with: bin/rails fond:codegen

      import { useMutation, type Mutation } from "fond";
      import type { ClCoMutCreateParams, ClCoMutUpdateParams, ClCoMutUpdateProps } from "./types";

      export function useClCoMutCreate(): Mutation<ClCoMutCreateParams, null> {
        return useMutation<ClCoMutCreateParams, null>("/mut", "post", []);
      }

      export function useClCoMutUpdate(): Mutation<ClCoMutUpdateParams, ClCoMutUpdateProps> {
        return useMutation<ClCoMutUpdateParams, ClCoMutUpdateProps>("/mut/:id", "patch", ["id"]);
      }
    TS

    assert_equal expected, generator.hooks_ts
  ensure
    remove_pages(:ClCoMutCreateMutation, :ClCoMutUpdateMutation)
  end

  def test_hooks_ts_pages_and_mutations_combined
    index_page = build_page("ClCoCombIndexPage", props: build_props(:total, Integer))
    create_mutation = build_mutation("ClCoCombCreateMutation", params: build_params(:name, String))

    generator = Fond::Codegen::Generator.new(
      pages: [index_page],
      bindings: [binding_for(index_page, "/comb", [])],
      mutations: [create_mutation],
      mutation_bindings: [mutation_binding_for(create_mutation, "/comb", "POST", [])]
    )

    ts = generator.hooks_ts
    assert_includes ts, "import { useMutation, usePageProps, type Mutation } from \"fond\";"
    assert_includes ts, "import type { ClCoCombCreateParams, ClCoCombIndexProps } from \"./types\";"
    assert_includes ts, "export function useClCoCombIndex(): ClCoCombIndexProps {"
    assert_includes ts, "export function useClCoCombCreate(): Mutation<ClCoCombCreateParams, null> {"
  ensure
    remove_pages(:ClCoCombIndexPage, :ClCoCombCreateMutation)
  end

  def test_hooks_ts_mutation_sort_order_and_verb_lowercasing
    b_mutation = build_mutation("ClCoSortBMutation", params: build_params(:x, Integer))
    a_mutation = build_mutation("ClCoSortAMutation", params: build_params(:y, Integer))

    generator = Fond::Codegen::Generator.new(
      pages: [],
      bindings: [],
      mutations: [b_mutation, a_mutation],
      mutation_bindings: [
        mutation_binding_for(b_mutation, "/sort/b", "DELETE", []),
        mutation_binding_for(a_mutation, "/sort/a", "PUT", [])
      ]
    )

    ts = generator.hooks_ts
    a_index = ts.index("useClCoSortA")
    b_index = ts.index("useClCoSortB")
    assert_operator a_index, :<, b_index
    assert_includes ts, "\"delete\""
    assert_includes ts, "\"put\""
  ensure
    remove_pages(:ClCoSortBMutation, :ClCoSortAMutation)
  end

  def test_hooks_ts_unchanged_with_no_mutations
    index_page = build_page("ClCoNoMutIndexPage", props: build_props(:total, Integer))

    generator = Fond::Codegen::Generator.new(
      pages: [index_page],
      bindings: [binding_for(index_page, "/no-mut", [])],
      mutations: [],
      mutation_bindings: []
    )

    refute_includes generator.hooks_ts, "useMutation"
    refute_includes generator.hooks_ts, "Mutation<"
    assert_includes generator.hooks_ts, "import { usePageProps } from \"fond\";"
  ensure
    remove_pages(:ClCoNoMutIndexPage)
  end

  def test_types_ts_discovers_mutation_params_and_nested_dtos
    line_item_dto = Class.new(T::Struct) { const :sku, String }
    Object.const_set(:ClCoMutLineItemDTO, line_item_dto)
    params = Class.new(T::Struct) do
      const :customer_name, String
      const :line_items, T::Array[line_item_dto]
    end
    mutation = build_mutation("ClCoMutTypesCreateMutation", params: params)

    generator = Fond::Codegen::Generator.new(
      pages: [],
      bindings: [],
      mutations: [mutation],
      mutation_bindings: [mutation_binding_for(mutation, "/mut-types", "POST", [])]
    )

    ts = generator.types_ts
    assert_includes ts, "export interface ClCoMutTypesCreateParams {"
    assert_includes ts, "customerName: string;"
    assert_includes ts, "lineItems: ClCoMutLineItemDTO[];"
    assert_includes ts, "export interface ClCoMutLineItemDTO {\n  sku: string;\n}"
  ensure
    remove_pages(:ClCoMutTypesCreateMutation, :ClCoMutLineItemDTO)
  end

  def test_mutation_name_collision_raises
    outer = Module.new
    Object.const_set(:ClCoMutNameCollision, outer)

    page = Class.new(Fond::Page)
    outer.const_set(:CreatePage, page)
    page.const_set(:Props, build_props(:ok, T::Boolean))

    mutation = Class.new(Fond::Mutation)
    outer.const_set(:CreateMutation, mutation)
    mutation.const_set(:Params, build_params(:name, String))

    generator = Fond::Codegen::Generator.new(
      pages: [page],
      bindings: [binding_for(page, "/mut-collision", [])],
      mutations: [mutation],
      mutation_bindings: [mutation_binding_for(mutation, "/mut-collision", "POST", [])]
    )

    error = assert_raises(Fond::Error) { generator.hooks_ts }
    assert_match(/ClCoMutNameCollisionCreate/, error.message)
  ensure
    Object.send(:remove_const, :ClCoMutNameCollision) if Object.const_defined?(:ClCoMutNameCollision)
  end

  def test_mutation_without_params_raises
    mutation = Class.new(Fond::Mutation)
    Object.const_set(:ClCoNoParamsMutation, mutation)

    error = assert_raises(Fond::Error) do
      Fond::Codegen::Generator.new(
        pages: [],
        bindings: [],
        mutations: [mutation],
        mutation_bindings: []
      )
    end
    assert_match(/ClCoNoParamsMutation/, error.message)
    assert_match(/Params/, error.message)
  ensure
    remove_pages(:ClCoNoParamsMutation)
  end

  def test_determinism_across_hooks_with_mutations
    create_mutation = build_mutation("ClCoDetMutCreateMutation", params: build_params(:a, Integer))
    bindings = [mutation_binding_for(create_mutation, "/det-mut", "POST", [])]

    first = Fond::Codegen::Generator.new(pages: [], bindings: [], mutations: [create_mutation], mutation_bindings: bindings)
    second = Fond::Codegen::Generator.new(pages: [], bindings: [], mutations: [create_mutation], mutation_bindings: bindings)

    assert_equal first.hooks_ts, second.hooks_ts
    assert_equal first.types_ts, second.types_ts
  ensure
    remove_pages(:ClCoDetMutCreateMutation)
  end

  def test_write_and_check_roundtrip_with_mutations
    page = build_page("ClCoWriteMutPage", props: build_props(:a, Integer))
    mutation = build_mutation("ClCoWriteMutCreateMutation", params: build_params(:b, Integer))

    generator = Fond::Codegen::Generator.new(
      pages: [page],
      bindings: [binding_for(page, "/write-mut", [])],
      mutations: [mutation],
      mutation_bindings: [mutation_binding_for(mutation, "/write-mut/create", "POST", [])]
    )

    Dir.mktmpdir do |dir|
      changed = generator.write(dir)
      names = %w[types.ts pages.ts hooks.ts paths.ts]
      expected_paths = names.map { |n| File.join(dir, n) }
      assert_equal expected_paths.sort, changed.sort
      assert generator.check(dir)
      assert_equal [], generator.write(dir)
    end
  ensure
    remove_pages(:ClCoWriteMutPage, :ClCoWriteMutCreateMutation)
  end

  private

  def binding_for(page, path, required_params)
    Fond::Routes::Binding.new(page: page, path: path, verb: "GET", required_params: required_params)
  end

  def mutation_binding_for(mutation, path, verb, required_params)
    Fond::Routes::Binding.new(page: mutation, path: path, verb: verb, required_params: required_params)
  end

  def build_props(name, type)
    Class.new(T::Struct) { const name, type }
  end

  def build_params(name, type)
    Class.new(T::Struct) { const name, type }
  end

  def build_page(name, props:, params: nil)
    page = Class.new(Fond::Page)
    Object.const_set(name, page)
    page.const_set(:Params, params) if params
    page.const_set(:Props, props)
    page
  end

  def build_mutation(name, params:, props: nil)
    mutation = Class.new(Fond::Mutation)
    Object.const_set(name, mutation)
    mutation.const_set(:Params, params)
    mutation.const_set(:Props, props) if props
    mutation
  end

  def remove_pages(*names)
    names.each { |n| Object.send(:remove_const, n) if Object.const_defined?(n) }
  end
end
