# frozen_string_literal: true

require_relative "test_helper"
require "fond/routes"
require "tmpdir"

class ClientCodegenTest < Minitest::Test
  def setup
    Fond::Registry.reset!
  end

  def test_pages_ts_content
    index_page = build_page("ClCoOrdersIndexPage", props: build_props(:total, Integer))
    show_page = build_page("ClCoOrdersShowPage", props: build_props(:name, String))

    generator = Fond::Codegen::Generator.new(
      pages: [show_page, index_page],
      bindings: [
        binding_for(show_page, "/orders/:id", %w[id]),
        binding_for(index_page, "/orders", [])
      ]
    )

    expected = <<~TS
      // Generated by fond. Do not edit.
      // Regenerate with: bin/rails fond:codegen

      export const pages = {
        "cl_co_orders_index": () => import("../pages/cl_co_orders_index"),
        "cl_co_orders_show": () => import("../pages/cl_co_orders_show"),
      };
      export type PageComponentName = keyof typeof pages;
    TS

    assert_equal expected, generator.pages_ts
  ensure
    remove_pages(:ClCoOrdersIndexPage, :ClCoOrdersShowPage)
  end

  def test_hooks_ts_content
    index_page = build_page("ClCoHooksIndexPage", props: build_props(:total, Integer))
    show_page = build_page("ClCoHooksShowPage", props: build_props(:name, String), params: build_params(:id, Integer))

    generator = Fond::Codegen::Generator.new(
      pages: [show_page, index_page],
      bindings: [
        binding_for(show_page, "/hooks/:id", %w[id]),
        binding_for(index_page, "/hooks", [])
      ]
    )

    expected = <<~TS
      // Generated by fond. Do not edit.
      // Regenerate with: bin/rails fond:codegen

      import { usePageProps } from "fond";
      import type { ClCoHooksIndexProps, ClCoHooksShowProps } from "./types";

      export function useClCoHooksIndex(): ClCoHooksIndexProps {
        return usePageProps<ClCoHooksIndexProps>("cl_co_hooks_index");
      }

      export function useClCoHooksShow(): ClCoHooksShowProps {
        return usePageProps<ClCoHooksShowProps>("cl_co_hooks_show");
      }
    TS

    assert_equal expected, generator.hooks_ts
  ensure
    remove_pages(:ClCoHooksIndexPage, :ClCoHooksShowPage)
  end

  def test_paths_ts_covers_all_signature_shapes
    # required :id, present on Params -> Pick/Omit
    show_page = build_page("ClCoPathsShowPage", props: build_props(:name, String), params: build_params(:id, Integer))
    # optional Params only -> Partial<X>
    index_page = build_page("ClCoPathsIndexPage", props: build_props(:total, Integer), params: build_params(:page, Integer))
    # no Params struct, no required params -> ()
    plain_page = build_page("ClCoPathsPlainPage", props: build_props(:ok, T::Boolean))
    # required :token, not a field of Params -> fallback with & Partial<X>
    legacy_page = build_page(
      "ClCoPathsLegacyPage",
      props: build_props(:ok, T::Boolean),
      params: build_params(:page, Integer)
    )
    # required :token, no Params struct at all -> plain fallback, no import
    bare_page = build_page("ClCoPathsBarePage", props: build_props(:ok, T::Boolean))

    generator = Fond::Codegen::Generator.new(
      pages: [show_page, index_page, plain_page, legacy_page, bare_page],
      bindings: [
        binding_for(show_page, "/paths/:id", %w[id]),
        binding_for(index_page, "/paths", []),
        binding_for(plain_page, "/paths/plain", []),
        binding_for(legacy_page, "/paths/legacy/:token", %w[token]),
        binding_for(bare_page, "/paths/bare/:token", %w[token])
      ]
    )

    ts = generator.paths_ts

    assert_includes ts, "import type { ClCoPathsIndexParams, ClCoPathsLegacyParams, ClCoPathsShowParams } from \"./types\";"
    assert_includes ts, "clCoPathsShow: (params: Pick<ClCoPathsShowParams, \"id\"> & Partial<Omit<ClCoPathsShowParams, \"id\">>) =>\n    buildPath(\"/paths/:id\", [\"id\"], params),"
    assert_includes ts, "clCoPathsIndex: (params?: Partial<ClCoPathsIndexParams>) =>\n    buildPath(\"/paths\", [], params),"
    assert_includes ts, "clCoPathsPlain: () =>\n    buildPath(\"/paths/plain\", []),"
    assert_includes ts, "clCoPathsLegacy: (params: { token: string | number } & Partial<ClCoPathsLegacyParams>) =>\n    buildPath(\"/paths/legacy/:token\", [\"token\"], params),"
    assert_includes ts, "clCoPathsBare: (params: { token: string | number }) =>\n    buildPath(\"/paths/bare/:token\", [\"token\"], params),"
  ensure
    remove_pages(:ClCoPathsShowPage, :ClCoPathsIndexPage, :ClCoPathsPlainPage, :ClCoPathsLegacyPage, :ClCoPathsBarePage)
  end

  def test_nested_module_page_naming
    outer = Module.new
    Object.const_set(:ClCoAdmin, outer)
    inner = Module.new
    outer.const_set(:Orders, inner)
    page = Class.new(Fond::Page)
    inner.const_set(:IndexPage, page)
    page.const_set(:Props, build_props(:total, Integer))

    assert_equal "cl_co_admin/orders/index", page.component_name

    generator = Fond::Codegen::Generator.new(
      pages: [page],
      bindings: [binding_for(page, "/admin/orders", [])]
    )

    assert_includes generator.hooks_ts, "export function useClCoAdminOrdersIndex(): ClCoAdminOrdersIndexProps {"
    assert_includes generator.paths_ts, "clCoAdminOrdersIndex: () =>\n    buildPath(\"/admin/orders\", []),"
  ensure
    Object.send(:remove_const, :ClCoAdmin) if Object.const_defined?(:ClCoAdmin)
  end

  def test_determinism_across_all_files
    a_page = build_page("ClCoDetAPage", props: build_props(:a, Integer))
    b_page = build_page("ClCoDetBPage", props: build_props(:b, Integer))
    bindings = [binding_for(a_page, "/det-a", []), binding_for(b_page, "/det-b", [])]

    first = Fond::Codegen::Generator.new(pages: [b_page, a_page], bindings: bindings)
    second = Fond::Codegen::Generator.new(pages: [b_page, a_page], bindings: bindings)

    assert_equal first.pages_ts, second.pages_ts
    assert_equal first.hooks_ts, second.hooks_ts
    assert_equal first.paths_ts, second.paths_ts
  ensure
    remove_pages(:ClCoDetAPage, :ClCoDetBPage)
  end

  def test_write_and_check_roundtrip_over_four_files
    page = build_page("ClCoWritePage", props: build_props(:a, Integer))
    generator = Fond::Codegen::Generator.new(pages: [page], bindings: [binding_for(page, "/write", [])])

    Dir.mktmpdir do |dir|
      changed = generator.write(dir)
      names = %w[types.ts pages.ts hooks.ts paths.ts]
      expected_paths = names.map { |n| File.join(dir, n) }
      assert_equal expected_paths.sort, changed.sort
      assert generator.check(dir)

      assert_equal [], generator.write(dir)

      File.write(File.join(dir, "pages.ts"), "tampered")
      refute generator.check(dir)

      recovered = generator.write(dir)
      assert_equal [File.join(dir, "pages.ts")], recovered
      assert generator.check(dir)
    end
  ensure
    remove_pages(:ClCoWritePage)
  end

  def test_pages_import_prefix_override
    page = build_page("ClCoPrefixPage", props: build_props(:a, Integer))
    original_prefix = Fond.config.pages_import_prefix
    Fond.config.pages_import_prefix = "@/pages/"

    generator = Fond::Codegen::Generator.new(pages: [page], bindings: [binding_for(page, "/prefix", [])])
    assert_includes generator.pages_ts, 'import("@/pages/cl_co_prefix")'
  ensure
    Fond.config.pages_import_prefix = original_prefix
    remove_pages(:ClCoPrefixPage)
  end

  private

  def binding_for(page, path, required_params)
    Fond::Routes::Binding.new(page: page, path: path, verb: "GET", required_params: required_params)
  end

  def build_props(name, type)
    Class.new(T::Struct) { const name, type }
  end

  def build_params(name, type)
    Class.new(T::Struct) { const name, type }
  end

  def build_page(name, props:, params: nil)
    page = Class.new(Fond::Page)
    Object.const_set(name, page)
    page.const_set(:Params, params) if params
    page.const_set(:Props, props)
    page
  end

  def remove_pages(*names)
    names.each { |n| Object.send(:remove_const, n) if Object.const_defined?(n) }
  end
end
