# frozen_string_literal: true

require_relative "test_helper"
require "tmpdir"

class GeneratorTest < Minitest::Test
  class GenOrderZStatus < T::Enum
    enums do
      OPEN = new("open")
    end
  end

  class GenEnumStatus < T::Enum
    enums do
      OPEN = new("open")
      SHIPPED = new("shipped")
    end
  end

  def setup
    Fond::Registry.reset!
  end

  def test_basic_generation_and_naming
    module_ = Module.new
    Object.const_set(:GenBasicOrders, module_)

    order_dto = Class.new(T::Struct) do
      const :id, Integer
      const :total_count, Integer
    end
    module_.const_set(:OrderDTO, order_dto)

    index_page = Class.new(Fond::Page)
    module_.const_set(:IndexPage, index_page)

    params = Class.new(T::Struct) { const :page, Integer, default: 1 }
    index_page.const_set(:Params, params)

    props = Class.new(T::Struct) { const :orders, T::Array[order_dto] }
    index_page.const_set(:Props, props)

    generator = Fond::Codegen::Generator.new(pages: [index_page])
    ts = generator.types_ts

    assert_includes ts, "// Generated by fond. Do not edit."
    assert_includes ts, "// Regenerate with: bin/rails fond:codegen"
    assert_includes ts, "export interface GenBasicOrdersIndexParams {\n  page: number;\n}"
    assert_includes ts, "export interface GenBasicOrdersIndexProps {\n  orders: GenBasicOrdersOrderDTO[];\n}"
    assert_includes ts, "export interface GenBasicOrdersOrderDTO {\n  id: number;\n  totalCount: number;\n}"
  ensure
    Object.send(:remove_const, :GenBasicOrders) if Object.const_defined?(:GenBasicOrders)
  end

  def test_camel_case_field_names
    props = Class.new(T::Struct) do
      const :total_count, Integer
      const :is_active, T::Boolean
    end
    page = build_page("GenCamelPage", props: props)

    ts = Fond::Codegen::Generator.new(pages: [page]).types_ts
    assert_includes ts, "totalCount: number;"
    assert_includes ts, "isActive: boolean;"
  end

  def test_alphabetical_ordering_of_structs_and_enums
    a_struct = Class.new(T::Struct) { const :x, Integer }
    Object.const_set(:GenAStruct, a_struct)

    z_struct = Class.new(T::Struct) do
      const :status, GenOrderZStatus
    end
    Object.const_set(:GenZStruct, z_struct)

    props = Class.new(T::Struct) do
      const :z, z_struct
      const :a, a_struct
    end
    page = build_page("GenOrderingPage", props: props)

    ts = Fond::Codegen::Generator.new(pages: [page]).types_ts
    a_index = ts.index("export interface GenAStruct")
    z_index = ts.index("export interface GenZStruct")
    refute_nil a_index
    refute_nil z_index
    assert_operator a_index, :<, z_index
  ensure
    Object.send(:remove_const, :GenAStruct) if Object.const_defined?(:GenAStruct)
    Object.send(:remove_const, :GenZStruct) if Object.const_defined?(:GenZStruct)
  end

  def test_deterministic_output
    props = Class.new(T::Struct) do
      const :a, Integer
      const :b, T::Array[T.any(Integer, String)]
    end
    page = build_page("GenDeterministicPage", props: props)

    first = Fond::Codegen::Generator.new(pages: [page]).types_ts
    second = Fond::Codegen::Generator.new(pages: [page]).types_ts
    assert_equal first, second
    assert_equal first.bytesize, second.bytesize
  end

  def test_nilable_field_is_not_optional
    props = Class.new(T::Struct) do
      const :maybe, T.nilable(String)
    end
    page = build_page("GenNilablePage", props: props)

    ts = Fond::Codegen::Generator.new(pages: [page]).types_ts
    assert_includes ts, "maybe: string | null;"
    refute_includes ts, "maybe?:"
  end

  def test_discriminated_union_literal_type_field
    shipped = Class.new(T::Struct) do
      const :type, String, default: "shipped"
      const :tracking, String
    end
    Object.const_set(:GenShippedEvent, shipped)

    cancelled = Class.new(T::Struct) do
      const :type, String, default: "cancelled"
      const :reason, String
    end
    Object.const_set(:GenCancelledEvent, cancelled)

    props = Class.new(T::Struct) do
      const :event, T.any(GenShippedEvent, GenCancelledEvent)
    end
    page = build_page("GenDiscriminatedPage", props: props)

    ts = Fond::Codegen::Generator.new(pages: [page]).types_ts
    assert_includes ts, "type: \"shipped\";"
    assert_includes ts, "type: \"cancelled\";"
  ensure
    Object.send(:remove_const, :GenShippedEvent) if Object.const_defined?(:GenShippedEvent)
    Object.send(:remove_const, :GenCancelledEvent) if Object.const_defined?(:GenCancelledEvent)
  end

  def test_enum_type_alias_emitted
    props = Class.new(T::Struct) { const :status, GenEnumStatus }
    page = build_page("GenEnumPage", props: props)

    ts = Fond::Codegen::Generator.new(pages: [page]).types_ts
    assert_includes ts, "export type GeneratorTestGenEnumStatus = \"open\" | \"shipped\";"
  end

  def test_iso_date_aliases_only_emitted_when_referenced
    props = Class.new(T::Struct) { const :created_at, Time }
    page = build_page("GenDatePage", props: props)

    ts = Fond::Codegen::Generator.new(pages: [page]).types_ts
    assert_includes ts, "export type ISODateTime = string;"
    refute_includes ts, "export type ISODate = string;"
  end

  def test_no_date_aliases_when_unused
    props = Class.new(T::Struct) { const :a, Integer }
    page = build_page("GenNoDatePage", props: props)

    ts = Fond::Codegen::Generator.new(pages: [page]).types_ts
    refute_includes ts, "ISODate"
  end

  def test_collision_raises
    outer = Module.new
    Object.const_set(:GenCollision, outer)

    catalog_page_ns = Module.new
    outer.const_set(:CatalogPage, catalog_page_ns)
    dto_one = Class.new(T::Struct) { const :id, Integer }
    catalog_page_ns.const_set(:ProductDTO, dto_one)

    catalog_ns = Module.new
    outer.const_set(:Catalog, catalog_ns)
    dto_two = Class.new(T::Struct) { const :id, Integer }
    catalog_ns.const_set(:ProductDTO, dto_two)

    props = Class.new(T::Struct) do
      const :a, dto_one
      const :b, dto_two
    end
    page = build_page("GenCollisionPage", props: props)

    error = assert_raises(Fond::Error) { Fond::Codegen::Generator.new(pages: [page]) }
    assert_match(/GenCollisionCatalogProductDTO/, error.message)
    assert_match(/ProductDTO/, error.message)
  ensure
    Object.send(:remove_const, :GenCollision) if Object.const_defined?(:GenCollision)
  end

  def test_write_and_check_roundtrip
    props = Class.new(T::Struct) { const :a, Integer }
    page = build_page("GenWritePage", props: props)
    bindings = [Fond::Routes::Binding.new(page: page, path: "/gen-write", verb: "GET", required_params: [])]
    generator = Fond::Codegen::Generator.new(pages: [page], bindings: bindings)

    Dir.mktmpdir do |dir|
      changed = generator.write(dir)
      paths = %w[types.ts pages.ts hooks.ts paths.ts].map { |name| File.join(dir, name) }
      assert_equal paths.sort, changed.sort
      paths.each { |path| assert File.exist?(path) }
      assert_equal generator.types_ts, File.read(paths[0])
      assert generator.check(dir)

      changed_again = generator.write(dir)
      assert_equal [], changed_again

      File.write(File.join(dir, "pages.ts"), "tampered")
      refute generator.check(dir)
    end
  end

  def test_check_false_when_file_missing
    props = Class.new(T::Struct) { const :a, Integer }
    page = build_page("GenMissingPage", props: props)
    bindings = [Fond::Routes::Binding.new(page: page, path: "/gen-missing", verb: "GET", required_params: [])]
    generator = Fond::Codegen::Generator.new(pages: [page], bindings: bindings)

    Dir.mktmpdir do |dir|
      refute generator.check(dir)
    end
  end

  def test_generator_uses_registry_by_default
    module_ = Module.new
    Object.const_set(:GenRegistryNs, module_)
    page_class = Class.new(Fond::Page)
    module_.const_set(:WidgetPage, page_class)
    props = Class.new(T::Struct) { const :a, Integer }
    page_class.const_set(:Props, props)

    generator = Fond::Codegen::Generator.new
    assert_includes generator.types_ts, "export interface GenRegistryNsWidgetProps"
  ensure
    Object.send(:remove_const, :GenRegistryNs) if Object.const_defined?(:GenRegistryNs)
  end

  private

  def build_page(name, params: nil, props:)
    page = Class.new(Fond::Page)
    Object.const_set(name, page)
    page.const_set(:Params, params) if params
    page.const_set(:Props, props)
    page
  end
end
