# typed: false
# frozen_string_literal: true

require "fileutils"

module Fond
  module Codegen
    # Discovers structs/enums reachable from page Params/Props and renders
    # types.ts, pages.ts, hooks.ts, and paths.ts.
    class Generator
      HEADER = ["// Generated by fond. Do not edit.", "// Regenerate with: bin/rails fond:codegen"].freeze
      FILE_NAMES = %w[types.ts pages.ts hooks.ts paths.ts].freeze

      def initialize(pages: Fond::Registry.concrete_pages,
                      bindings: defined?(Rails) ? Fond::Routes.page_bindings : [])
        @pages = pages
        @bindings = bindings
        @ts_names = {}
        @name_cache = {}
        @emitter = TsEmitter.new(name_for: method(:name_for))
        @structs = {}
        @enums = {}

        discover!
      end

      def types_ts
        @types_ts ||= build_ts
      end

      def pages_ts
        @pages_ts ||= build_pages_ts
      end

      def hooks_ts
        @hooks_ts ||= build_hooks_ts
      end

      def paths_ts
        @paths_ts ||= build_paths_ts
      end

      def write(dir)
        FileUtils.mkdir_p(dir)

        files.each_with_object([]) do |(name, content), changed|
          path = File.join(dir, name)
          next if File.exist?(path) && File.read(path) == content

          File.write(path, content)
          changed << path
        end
      end

      def check(dir)
        files.all? do |name, content|
          path = File.join(dir, name)
          File.exist?(path) && File.read(path) == content
        end
      end

      private

      def files
        {
          "types.ts" => types_ts,
          "pages.ts" => pages_ts,
          "hooks.ts" => hooks_ts,
          "paths.ts" => paths_ts
        }
      end

      def sorted_pages
        @sorted_pages ||= @pages.sort_by(&:component_name)
      end

      def binding_for(page)
        @binding_by_page ||= @bindings.each_with_object({}) { |b, h| h[b.page] = b }
        @binding_by_page.fetch(page) { raise Fond::Error, "fond: no route binding for #{page.name}" }
      end

      def name_for(klass)
        return @name_cache[klass] if @name_cache.key?(klass)

        segments = klass.name.split("::").map { |s| s.end_with?("Page") ? s.delete_suffix("Page") : s }
        ts_name = segments.join

        existing = @ts_names[ts_name]
        if existing && existing != klass
          raise Fond::Error, "fond: \"#{ts_name}\" is generated by both #{existing.name} and #{klass.name}"
        end

        @ts_names[ts_name] = klass
        @name_cache[klass] = ts_name
      end

      def discover!
        queue = []
        @pages.each do |page|
          queue << page.params_class if page.params_class
          queue << page.props_class
        end

        until queue.empty?
          klass = queue.shift
          next if @structs.key?(klass)

          process_struct(klass)

          @emitter.referenced.each do |ref|
            if ref < T::Struct
              queue << ref unless @structs.key?(ref)
            elsif ref < T::Enum
              register_enum(ref) unless @enums.key?(ref)
            end
          end
        end
      end

      def process_struct(klass)
        name = name_for(klass)
        fields = klass.props.map do |prop_name, prop|
          [camelize(prop_name), field_type(prop_name, prop)]
        end

        @structs[klass] = { name: name, fields: fields }
      end

      def field_type(prop_name, prop)
        if prop_name == :type && prop[:default].is_a?(String) &&
           prop[:type_object].is_a?(T::Types::Simple) && prop[:type_object].raw_type == String
          prop[:default].inspect
        else
          @emitter.emit(prop[:type_object])
        end
      end

      def register_enum(klass)
        name = name_for(klass)
        @enums[klass] = { name: name, values: klass.values.map(&:serialize) }
      end

      def camelize(prop_name)
        Fond::Naming.camelize(prop_name)
      end

      def build_ts
        lines = HEADER.dup

        if @emitter.uses_date? || @emitter.uses_date_time?
          lines << ""
          lines << "export type ISODate = string;" if @emitter.uses_date?
          lines << "export type ISODateTime = string;" if @emitter.uses_date_time?
        end

        enums_sorted = @enums.values.sort_by { |e| e[:name] }
        if enums_sorted.any?
          lines << ""
          enums_sorted.each do |e|
            values = e[:values].map(&:inspect).join(" | ")
            lines << "export type #{e[:name]} = #{values};"
          end
        end

        structs_sorted = @structs.values.sort_by { |s| s[:name] }
        structs_sorted.each do |s|
          lines << ""
          lines << "export interface #{s[:name]} {"
          s[:fields].each do |field_name, ts_type|
            lines << "  #{field_name}: #{ts_type};"
          end
          lines << "}"
        end

        "#{lines.join("\n")}\n"
      end

      def build_pages_ts
        prefix = Fond.config.pages_import_prefix
        lines = HEADER.dup
        lines << ""
        lines << "export const pages = {"
        sorted_pages.each do |page|
          component_name = page.component_name
          lines << "  #{component_name.inspect}: () => import(#{"#{prefix}#{component_name}".inspect}),"
        end
        lines << "};"
        lines << "export type PageComponentName = keyof typeof pages;"

        "#{lines.join("\n")}\n"
      end

      def build_hooks_ts
        referenced = sorted_pages.map { |page| name_for(page.props_class) }.uniq.sort

        lines = HEADER.dup
        lines << ""
        lines << "import { usePageProps } from \"fond\";"
        lines << "import type { #{referenced.join(', ')} } from \"./types\";" if referenced.any?

        sorted_pages.each do |page|
          hook_name = "use#{name_for(page)}"
          props_name = name_for(page.props_class)

          lines << ""
          lines << "export function #{hook_name}(): #{props_name} {"
          lines << "  return usePageProps<#{props_name}>(#{page.component_name.inspect});"
          lines << "}"
        end

        "#{lines.join("\n")}\n"
      end

      def build_paths_ts
        entries = sorted_pages.map { |page| path_entry(page) }
        referenced = entries.map { |e| e[:referenced_type] }.compact.uniq.sort

        lines = HEADER.dup
        lines << ""
        lines << "import { buildPath } from \"fond\";"
        lines << "import type { #{referenced.join(', ')} } from \"./types\";" if referenced.any?
        lines << ""
        lines << "export const paths = {"
        entries.each do |e|
          lines << "  #{e[:key]}: #{e[:signature]} =>"
          lines << "    #{e[:call]},"
        end
        lines << "};"

        "#{lines.join("\n")}\n"
      end

      def path_entry(page)
        route_binding = binding_for(page)
        params_class = page.params_class
        required_params = route_binding.required_params
        camel_params = required_params.map { |p| Fond::Naming.camelize(p) }

        signature, call_args_params, referenced_type = path_signature(params_class, required_params, camel_params)

        path_params_array = "[#{camel_params.map(&:inspect).join(', ')}]"
        call_args = [route_binding.path.inspect, path_params_array, call_args_params].compact.join(", ")

        {
          key: path_key(page.component_name),
          signature: signature,
          call: "buildPath(#{call_args})",
          referenced_type: referenced_type
        }
      end

      def path_signature(params_class, required_params, camel_params)
        if required_params.empty?
          return ["()", nil, nil] unless params_class

          name = name_for(params_class)
          ["(params?: Partial<#{name}>)", "params", name]
        else
          struct_fields = params_class ? params_class.props.keys.map(&:to_s) : []
          all_present = params_class && required_params.all? { |p| struct_fields.include?(p) }

          if all_present
            name = name_for(params_class)
            keys = camel_params.map(&:inspect).join(" | ")
            ["(params: Pick<#{name}, #{keys}> & Partial<Omit<#{name}, #{keys}>>)", "params", name]
          else
            fields = camel_params.map { |k| "#{k}: string | number" }.join("; ")
            if params_class
              name = name_for(params_class)
              ["(params: { #{fields} } & Partial<#{name}>)", "params", name]
            else
              ["(params: { #{fields} })", "params", nil]
            end
          end
        end
      end

      def path_key(component_name)
        parts = component_name.split("/")
        parts.each_with_index.map do |part, i|
          camel = Fond::Naming.camelize(part)
          i.zero? ? camel : camel[0].upcase + camel[1..]
        end.join
      end
    end
  end
end
