# typed: false
# frozen_string_literal: true

require "fileutils"

module Fond
  module Codegen
    # Discovers structs/enums reachable from page Params/Props and renders types.ts.
    class Generator
      def initialize(pages: Fond::Registry.concrete_pages)
        @pages = pages
        @ts_names = {}
        @name_cache = {}
        @emitter = TsEmitter.new(name_for: method(:name_for))
        @structs = {}
        @enums = {}

        discover!
      end

      def types_ts
        @types_ts ||= build_ts
      end

      def write(dir)
        FileUtils.mkdir_p(dir)
        path = File.join(dir, "types.ts")
        content = types_ts

        return [] if File.exist?(path) && File.read(path) == content

        File.write(path, content)
        [path]
      end

      def check(dir)
        path = File.join(dir, "types.ts")
        File.exist?(path) && File.read(path) == types_ts
      end

      private

      def name_for(klass)
        return @name_cache[klass] if @name_cache.key?(klass)

        segments = klass.name.split("::").map { |s| s.end_with?("Page") ? s.delete_suffix("Page") : s }
        ts_name = segments.join

        existing = @ts_names[ts_name]
        if existing && existing != klass
          raise Fond::Error, "fond: \"#{ts_name}\" is generated by both #{existing.name} and #{klass.name}"
        end

        @ts_names[ts_name] = klass
        @name_cache[klass] = ts_name
      end

      def discover!
        queue = []
        @pages.each do |page|
          queue << page.params_class if page.params_class
          queue << page.props_class
        end

        until queue.empty?
          klass = queue.shift
          next if @structs.key?(klass)

          process_struct(klass)

          @emitter.referenced.each do |ref|
            if ref < T::Struct
              queue << ref unless @structs.key?(ref)
            elsif ref < T::Enum
              register_enum(ref) unless @enums.key?(ref)
            end
          end
        end
      end

      def process_struct(klass)
        name = name_for(klass)
        fields = klass.props.map do |prop_name, prop|
          [camelize(prop_name), field_type(prop_name, prop)]
        end

        @structs[klass] = { name: name, fields: fields }
      end

      def field_type(prop_name, prop)
        if prop_name == :type && prop[:default].is_a?(String) &&
           prop[:type_object].is_a?(T::Types::Simple) && prop[:type_object].raw_type == String
          prop[:default].inspect
        else
          @emitter.emit(prop[:type_object])
        end
      end

      def register_enum(klass)
        name = name_for(klass)
        @enums[klass] = { name: name, values: klass.values.map(&:serialize) }
      end

      def camelize(prop_name)
        Fond::Naming.camelize(prop_name)
      end

      def build_ts
        lines = ["// Generated by fond. Do not edit.", "// Regenerate with: bin/rails fond:codegen"]

        if @emitter.uses_date? || @emitter.uses_date_time?
          lines << ""
          lines << "export type ISODate = string;" if @emitter.uses_date?
          lines << "export type ISODateTime = string;" if @emitter.uses_date_time?
        end

        enums_sorted = @enums.values.sort_by { |e| e[:name] }
        if enums_sorted.any?
          lines << ""
          enums_sorted.each do |e|
            values = e[:values].map(&:inspect).join(" | ")
            lines << "export type #{e[:name]} = #{values};"
          end
        end

        structs_sorted = @structs.values.sort_by { |s| s[:name] }
        structs_sorted.each do |s|
          lines << ""
          lines << "export interface #{s[:name]} {"
          s[:fields].each do |field_name, ts_type|
            lines << "  #{field_name}: #{ts_type};"
          end
          lines << "}"
        end

        "#{lines.join("\n")}\n"
      end
    end
  end
end
